version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:8080
        environment:
            APP_NAME: "conduit"
            APP_ENV: "local"
            APP_DEBUG: "true"
            APP_URL: "http://localhost"
            APP_LOG_LEVEL: "debug"
            DB_CONNECTION: "mysql"
            DB_HOST: "database"
            DB_PORT: "3306"
            DB_DATABASE: "realworld"
            DB_USERNAME: "realworld"
            DB_PASSWORD: "realworld"
            JWT_SECRET: "supersecretkeyyoushouldnotcommittogithub"
            CORS_ALLOWED_ORIGINS: "*"
        volumes:
            - .:/var/www
        container_name: app
    mysql:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: realworld
            MYSQL_PASSWORD: realworld
            MYSQL_USER: realworld
        container_name: database
