name: Test, Docker Build and Push
on:
  push:
    tags:
      - "*"
jobs:
  build-and-retest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Run Test Suite
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
          php_version: "8.0"
  docker-build-and-push:
    needs:  build-and-retest
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            meezaan/realworld-api:latest
            meezaan/realworld-api:${{ github.ref_name }}
      - name: Install Env Substring
        run: sudo apt-get update && sudo apt-get -y install gettext-base
      - name: Install Kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod u+x ./kubectl
      - name: Deploy
        run: |
          pwd
          ls -ls
          curl -o ./.k8s/deploy.sh https://raw.githubusercontent.com/islamic-network/k8s-deployment/master/deploy.sh
          chmod u+x ./.k8s/deploy.sh
          REF_NAME=${{ github.ref_name }}
          K8S_URL=${{ secrets.K8S_URL }}
          K8S_TOKEN=${{ secrets.K8S_TOKEN }}
          K8S_CA=${{ secrets.K8S_CA }}
          sh ./.k8s/deploy.sh
