name: Test, Build and Tag
on:
  push:
    branches:
      - "master"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Run Test Suite
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
          php_version: "8.0"
  create-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag Name
        id: vars
        run: echo ::set-output name=TAGNAME::$(date +"%Y-%m-%d-%H-%M")
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.TAGNAME }}
          release_name: Release ${{ steps.vars.outputs.TAGNAME }}
          body: |
            Automated release
          draft: false
          prerelease: false
