name: Test, Build and Tag
on:
  push:
    branches:
      - "master"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Run Test Suite
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
          php_version: "8.0"
  create-tag:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag Name
        id: vars
        run: echo ::set-output name=TAGNAME::$(date +"%Y-%m-%d-%H-%M")
      - run: echo "The new tag is " ${{ steps.vars.outputs.TAGNAME }}
      - uses: actions/checkout@v3
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.TAGNAME }}
